[project]
name = "bot-trap"
version = "0.1.0"
description = "Static file server that detects bad crawlers."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.11.5",
]
